### ISSUE TITLE
Updating Candy Calc

### ISSUE THREAD

**Issue by doctorC3** [richi3f/candy-calc#1]
Hello! I've noticed you have been working on other projects but I was wondering if you had plans on implementing BDSP and PLA pokemon to the Candy Calc?

**Comment by richi3f** [comment]
Hi there, sorry for the tardy reply! Exp. candies were unavailable in BDSP, and were limited in PLA, so I did not update the calculator until now. It has all Pokémon, including those introduced in PLA and Scarlet & Violet
